version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    ports:
      - "5050:5050"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    restart: always
