@startuml Manage Car (GET ONE)

header Rental Car Booking Diagram
footer Page %page% of %lastpage%
title "Manage Car (GET ONE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:cars" as routerCars
participant "<<controllers>>\n:cars" as controllersCars
participant "<<model>>\n:Car" as modelCar
database "<<MongoDB>>\n:cars" as CarsDatabase

client->server ++:req.get('/cars/:id')
server->routerCars ++:app.use('/cars',cars)
routerCars -> controllersCars ++:getCar()
controllersCars->modelCar ++:findById(req.params.id)
modelCar ->CarsDatabase ++: CarSchema
CarsDatabase --> modelCar --: car
controllersCars <-- modelCar --:car
controllersCars->client --:response

@enduml
